
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: kmltml/io-lab-docker-ci-public
    ports:
    - "5000:5000"
    links:
    - redis    
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
    - ./data:/data